# Generated by Django 3.1.2 on 2021-05-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='')),
                ('visible', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'App-Post',
            },
        ),
    ]
